spring.application.name: stock
spring.kafka:
  bootstrap-servers: localhost:29092
ioevent:
    prefix: DistributedTransactions
    group_id: stock
    api_key: 5fd1178a-c1cd-41bc-b62a-ffcf5b1ee1f0 #7e3f052e-1bcc-4077-a713-aab44d5b1117
    eureka:
      enabled: true
eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka