spring.application.name: customer
spring.kafka:
  bootstrap-servers: localhost:29092
ioevent:
    prefix: DistributedTransactions
    group_id: payment
    api_key: 7e3f052e-1bcc-4077-a713-aab44d5b1117 
    eureka:
      enabled: true
eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8085